### ISSUE TITLE
Error in client.py

### ISSUE THREAD

**Issue by KvEijden** [UtrechtUniversity/remindo-api#3]
When trying to import client I get the following error message:
>>> from remindo_api import client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/keesvaneijden/RSE/remindo-api/src/remindo_api/client.py", line 7, in <module>
    from .cluster import RemindoCluster
  File "/Users/keesvaneijden/RSE/remindo-api/src/remindo_api/cluster.py", line 18
    _cluster_dict: dict
                 ^
SyntaxError: invalid syntax

I'm running python 3.5 in an conda environment

**Comment by leonardovida** [comment]
@KvEijden Can you try to use Python 3.8 or higher and use the last release?

**Comment by KvEijden** [comment]
I did and didn't get this syntax error, but see new issue
